---
- name: test book
  hosts: localhost
  become: true
  connection: local
  tasks:
    - name: install apache2
      apt:
          name: apache2
          state: latest
    - name: run httpd
      service:
              name: apache2
              state: started
    - name: create content
      copy:
           content: "Ansible MFs"
           dest: /var/www/html/index.html  
